version: "3.7"

services: 
    vue-app: 
        build: .
        volumes: 
            - .:/app
        working_dir: /app
        ports: 
            - 8080:8080
        command: ['npm', 'run', 'serve']